export const type = {
  CANCEL_SUBSCRIPTION_REQUEST_REQUEST: "CANCEL_SUBSCRIPTION_REQUEST_REQUEST",
  CANCEL_SUBSCRIPTION_REQUEST_FAILURE: "CANCEL_SUBSCRIPTION_REQUEST_FAILURE",
  CANCEL_SUBSCRIPTION_REQUEST_SUCCESS: "CANCEL_SUBSCRIPTION_REQUEST_SUCCESS",
};
