export const type = {
    UPDATE_PASSWORD_ADDRESS_REQUEST: 'UPDATE_PASSWORD_ADDRESS_REQUEST',
    UPDATE_PASSWORD_ADDRESS_FAILURE: 'UPDATE_PASSWORD_ADDRESS_FAILURE',
    UPDATE_PASSWORD_ADDRESS_SUCCESS: 'UPDATE_PASSWORD_ADDRESS_SUCCESS',
    UPDATE_PASSWORD_ADDRESS_RESET: "UPDATE_PASSWORD_ADDRESS_RESET"
}