export const type = {
    UPDATE_EMAIL_ADDRESS_REQUEST: 'UPDATE_EMAIL_ADDRESS_REQUEST',
    UPDATE_EMAIL_ADDRESS_FAILURE: 'UPDATE_EMAIL_ADDRESS_FAILURE',
    UPDATE_EMAIL_ADDRESS_SUCCESS: 'UPDATE_EMAIL_ADDRESS_SUCCESS'
}