export const type = {
    UPDATE_PHONE_NUMBER_REQUEST: 'UPDATE_PHONE_NUMBER_REQUEST',
    UPDATE_PHONE_NUMBER_FAILURE: 'UPDATE_PHONE_NUMBER_FAILURE',
    UPDATE_PHONE_NUMBER_SUCCESS: 'UPDATE_PHONE_NUMBER_SUCCESS'
}