export const types = {
    GET_RECOMMENDEDMOVIES: 'GET_RECOMMENDEDMOVIES',
    GET_CONTINUEWATCHING: 'GET_CONTINUEWATCHING',
    GET_THEME_SUCCESS: "GET_THEME_SUCCESS",
    HOME_PAGE_CONTENT: 'HOME_PAGE_CONTENT'
}