export const types = {
  REMOVE_PAYMENT_METHOD_REQUESTED: 'REMOVE_PAYMENT_METHOD_REQUESTED',
  REMOVE_PAYMENT_METHOD_SUCCESS: 'REMOVE_PAYMENT_METHOD_SUCCESS',
  REMOVE_PAYMENT_METHOD_FAILURE: 'REMOVE_PAYMENT_METHOD_FAILURE',
}