export const signInConstants = {
  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  RESET_SIGIN: "RESET_SIGIN",
  RESET_RELOAD_STATUS: "RESET_RELOAD_STATUS",
  SIGNOUT: "SIGNOUT",
};

export const preAuthValidation = {
  EMAIL_ADDRESS_EXIST_REQUEST: "EMAIL_ADDRESS_EXIST_REQUEST",
  EMAIL_ADDRESS_RESET: "EMAIL_ADDRESS_RESET",
  EMAIL_ADDRESS_EXIST_SUCCESS: "EMAIL_ADDRESS_EXIST_SUCCESS",
  EMAIL_ADDRESS_EXIST_FAILURE: "EMAIL_ADDRESS_EXIST_FAILURE",
  SOCIAL_LOGIN_FAILURE: "SOCIAL_LOGIN_FAILURE"
};

export const resetPwdEmail = {
  RESET_PASSWORD_EMAIL_REQUEST: "RESET_PASSWORD_EMAIL_REQUEST",
  RESET_PASSWORD_EMAIL_SUCCESS: "RESET_PASSWORD_EMAIL_SUCCESS",
  RESET_PASSWORD_EMAIL_FAILURE: "RESET_PASSWORD_EMAIL_FAILURE",
  RESET_PASSWORD_EMAIL_INITIALIZE: "RESET_PASSWORD_EMAIL_INITIALIZE"
};

export const resetAccessToken = {
  RESET_ACCESS_TOKEN_REQUEST: "RESET_ACCESS_TOKEN_REQUEST",
  RESET_ACCESS_TOKEN_SUCCESS: "RESET_ACCESS_TOKEN_SUCCESS",
  RESET_ACCESS_TOKEN_FAILURE: "RESET_ACCESS_TOKEN_FAILURE",
};
